// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmpybodbozpycvieipuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcHlib2Rib3pweWN2aWVpcHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzYzNTMsImV4cCI6MjA2MTUxMjM1M30.LsPpBQk7OjmOBcoXnbT8KAzpLXHUz0E_JbpsIuZDYBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);